[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path = 'forge-cache'
offline = true

[rpc_endpoints]
arbitrum = "${ARBITRUM}"
ethereum = "${ETHEREUM}"
ethereum-mocks = "${ETHEREUM}"

# [fuzz]
# seed = 10

# [profile.default.fuzz]
# seed = 100

# [profile.default.invariant]
# runs = 100
# depth = 100


# See more config options https://github.com/foundry-rs/foundry/tree/master/config